import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Jetbus(props) {
  const { nodes, materials } = useGLTF('/Jetbus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.d_5.geometry} material={materials['d_5.0']} />
      <mesh castShadow receiveShadow geometry={nodes.d_7.geometry} material={materials['d_2.0']} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.zmd_2.geometry}
        material={materials['zmdl89.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bdlmpilar.geometry}
        material={materials['bdlmkaca.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bdlmpilar_2.geometry}
        material={materials['bdlmkaca.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pijakan.geometry}
        material={materials[' shift.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bdlm_4.geometry}
        material={materials['bdlmkaca.0']}
      />
      <group position={[-1.148, -1.337, 3.728]} rotation={[0, 0, 0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_lb.geometry}
          material={materials['wheel_lf.0']}
          position={[-0.056, -0.016, 0]}
          rotation={[0, 0, -0.001]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_lb_2.geometry}
            material={materials['wheel_lf_2.0']}
            position={[0, -0.017, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_lb_3.geometry}
            material={materials['wheel_lf_2.0']}
            position={[0, -0.017, 0]}
          />
        </mesh>
      </group>
      <group position={[-1.063, -1.334, 5.402]} rotation={[Math.PI / 4, 0.001, 0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_lm.geometry}
          material={materials['wheel_lf.0']}
          position={[0.122, -0.012, 0.014]}
          rotation={[-Math.PI / 4, 0, -0.001]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_lm_2.geometry}
            material={materials['wheel_lf_2.0']}
            position={[0, -0.017, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_lm_3.geometry}
            material={materials['wheel_lf_2.0']}
            position={[0, -0.017, 0]}
          />
        </mesh>
      </group>
      <group position={[1.159, -1.337, 3.728]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_rb.geometry}
          material={materials['wheel_lf.0']}
          position={[-0.061, -0.016, 0]}
          scale={[1.609, 1, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_rb_2.geometry}
            material={materials['wheel_lf_2.0']}
            position={[0, -0.017, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_rb_3.geometry}
            material={materials['wheel_lf_2.0']}
            position={[0, -0.017, 0]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_rb001.geometry}
          material={materials['wheel_lf.0']}
          position={[-2.305, -0.016, 0]}
          rotation={[0, 0, Math.PI]}
          scale={[1.609, 1, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_rb_3001.geometry}
            material={materials['wheel_lf_2.0']}
            position={[0, -0.017, 0]}
          />
        </mesh>
      </group>
      <group position={[1.045, -1.337, -4.086]} rotation={[Math.PI / 4, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_rf.geometry}
          material={materials['wheel_lf.0']}
          position={[0.223, -0.011, 0.012]}
          rotation={[-Math.PI / 4, 0, 0]}
          scale={[1.609, 1, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_rf_2.geometry}
            material={materials['wheel_lf_2.0']}
            position={[0, -0.017, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_rf_3.geometry}
            material={materials['wheel_lf_2.0']}
            position={[0, -0.017, 0]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_rf001.geometry}
          material={materials['wheel_lf.0']}
          position={[-2.36, -0.011, 0.012]}
          rotation={[-Math.PI / 4, 0, Math.PI]}
          scale={[1.609, 1, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_rf_2001.geometry}
            material={materials['wheel_lf_2.0']}
            position={[0, -0.017, 0]}
          />
        </mesh>
      </group>
      <group position={[1.045, -1.337, 5.402]} rotation={[Math.PI / 4, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_rm.geometry}
          material={materials['wheel_lf.0']}
          position={[0.223, -0.011, 0.012]}
          rotation={[-Math.PI / 4, 0, 0]}
          scale={[1.609, 1, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_rm_2.geometry}
            material={materials['wheel_lf_2.0']}
            position={[0, -0.017, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_rm_3.geometry}
            material={materials['wheel_lf_2.0']}
            position={[0, -0.017, 0]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_rm001.geometry}
          material={materials['wheel_lf.0']}
          position={[-2.36, -0.011, 0.012]}
          rotation={[-Math.PI / 4, 0, Math.PI]}
          scale={[1.609, 1, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_rm_2001.geometry}
            material={materials['wheel_lf_2.0']}
            position={[0, -0.017, 0]}
          />
        </mesh>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.alphajb5.geometry}
        material={materials['alphajb5.0']}
      />
      <group position={[1.488, -0.584, -6.619]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_rf_ok001.geometry}
          material={materials['housing.0']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_rf_ok_2.geometry}
          material={materials['bdlmkaca.0']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.skotlet.geometry}
        material={materials['skotlet.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bumperplastic.geometry}
        material={materials['bumperplastic.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chrbdyblkg.geometry}
        material={materials['chrbdyblkg.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chrface.geometry}
        material={materials['chrface.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chrfoglamp.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chrmuffler.geometry}
        material={materials['chrmuffler.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chrsldjb5.geometry}
        material={materials['headlamp.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chrtopi.geometry}
        material={materials['tatakanemblem.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.emblem.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.emblem_2.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.emblem_3.geometry}
        material={materials['tatakanemblem.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.emblemjetbus.geometry}
        material={materials['emblemjetbus.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grill.geometry}
        material={materials['grill.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kepet.geometry}
        material={materials['kepet.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kolongbannew.geometry}
        material={materials['kolongbannew.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lamp_blue.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lamp_red.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.listbodybasic.geometry}
        material={materials['emblemjetbus.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.listbodybasic_2.geometry}
        material={materials['emblemjetbus.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.listdepan.geometry}
        material={materials['emblemjetbus.0']}
        position={[0, 0, -2.738]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.listface.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.listkaca.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.listkacablkg.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.listkacakclblkg.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.listkapblkg.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.listtempartsld.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lmpbagasi.geometry}
        material={materials['lmpplat.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lmpblkgatas.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lmpbumper.geometry}
        material={materials['lmpplat.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lmpkacablkg.geometry}
        material={materials['emblemjetbus.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lmpplat.geometry}
        material={materials['lmpplat.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lmpseinspion.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lmpsudut.geometry}
        material={materials['lmpplat.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mirror.geometry}
        material={materials['mirror.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mirrorjb5.geometry}
        material={materials['tatakanemblem.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.panas_kalungan_LD9.geometry}
        material={materials['panas kalungan LD9.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.partlmpplat.geometry}
        material={materials['lmpplat.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.prtbdyblkg.geometry}
        material={materials['emblemjetbus.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.spionsopir.geometry}
        material={materials['emblemjetbus.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.temmuffler.geometry}
        material={materials['bumperplastic.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wiper.geometry}
        material={materials['emblemjetbus.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.headlamp_1.geometry}
        material={materials['headlamp.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.headlamp_2.geometry}
        material={materials['headlamp.1']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.headlamp_3.geometry}
        material={materials['headlamp.2']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.headlamp_4.geometry}
        material={materials['headlamp.3']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.emblemL.geometry}
        material={materials['tatakanemblem.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tatakanemblem.geometry}
        material={materials['tatakanemblem.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lmpsein_1.geometry}
        material={materials['chrbdyblkg.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lmpsein_2.geometry}
        material={materials['lmpsein.1']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.perpengaman_1.geometry}
        material={materials['emblemjetbus.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.perpengaman_2.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rearlamp_1.geometry}
        material={materials['rearlamp.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rearlamp_2.geometry}
        material={materials['rearlamp.1']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.housing.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backgrill.geometry}
        material={materials['backgrill.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bodybasicjb5.geometry}
        material={materials['bodybasicjb5.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grilljb5.geometry}
        material={materials['grilljb5.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platjb5001.geometry}
        material={materials['bodybasicjb5.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.spionjb5.geometry}
        material={materials['bodybasicjb5.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.topijb5.geometry}
        material={materials['bodybasicjb5.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kacalmp_1.geometry}
        material={materials.glass}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kacalmp_2.geometry}
        material={materials['kacalmp.1']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wing_lf_ok001.geometry}
        material={materials['housing.0']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wing_lf_ok_3.geometry}
        material={materials['lmpplat.0']}
      />
    </group>
  )
}

useGLTF.preload('/Jetbus.glb')